package provider

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/malico/docker-release/internal/docker"
)

// AngieProvider is a provider for the Angie web server (a drop-in nginx replacement)
type AngieProvider struct {
	configDir   string
	docker      *docker.Client
	serviceName string
}

// NewAngie creates a new Angie provider
func NewAngie(configDir string, dockerClient *docker.Client, serviceName string) *AngieProvider {
	return &AngieProvider{
		configDir:   configDir,
		docker:      dockerClient,
		serviceName: serviceName,
	}
}

// GenerateConfig creates an Angie upstream configuration file
func (p *AngieProvider) GenerateConfig(state *UpstreamState) error {
	if err := state.Validate(); err != nil {
		return err
	}

	conf := renderAngieUpstream(state)

	if err := os.MkdirAll(p.configDir, 0o755); err != nil {
		return fmt.Errorf("creating config dir: %w", err)
	}

	path := filepath.Join(p.configDir, state.Service+".conf")
	tmp := path + ".tmp"

	if err := os.WriteFile(tmp, []byte(conf), 0o644); err != nil {
		return fmt.Errorf("writing config: %w", err)
	}

	if err := os.Rename(tmp, path); err != nil {
		return fmt.Errorf("renaming config: %w", err)
	}

	return nil
}

// Reload signals Angie to reload its configuration
func (p *AngieProvider) Reload() error {
	if p.serviceName == "" {
		return nil
	}

	ctx := context.Background()

	ctr, err := p.docker.FindContainerByService(ctx, p.serviceName)
	if err != nil {
		return fmt.Errorf("resolving angie container %q: %w", p.serviceName, err)
	}

	if !matchesImage(ctr.Image, "angie", "nginx", "alpine") {
		return fmt.Errorf("container %q has unexpected image %q (want angie, nginx, or alpine-based)", p.serviceName, ctr.Image)
	}

	return p.docker.Exec(ctx, ctr.ID, []string{"angie", "-s", "reload"})
}

// renderAngieUpstream generates the upstream block for Angie
// Angie is a drop-in replacement for nginx, so the syntax is identical
func renderAngieUpstream(state *UpstreamState) string {
	var b strings.Builder

	fmt.Fprintf(&b, "# Generated by docker-release for Angie\n")
	fmt.Fprintf(&b, "upstream %s_upstream {\n", state.ResolveUpstreamName())

	switch state.Affinity {
	case "cookie":
		b.WriteString("    sticky cookie _srv path=/;\n")
	case "ip":
		fmt.Fprintf(&b, "    ip_hash;\n")
	default:
		fmt.Fprintf(&b, "    least_conn;\n")
	}

	for _, s := range state.Servers {
		fmt.Fprintf(&b, "    server %s", s.Addr)

		if s.Down {
			fmt.Fprintf(&b, " down")
		} else if s.Weight > 0 {
			fmt.Fprintf(&b, " weight=%d", s.Weight)
		}

		fmt.Fprintf(&b, ";\n")
	}

	if state.Keepalive > 0 {
		fmt.Fprintf(&b, "    keepalive %d;\n", state.Keepalive)
	}

	fmt.Fprintf(&b, "}\n")

	return b.String()
}
