package provider

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/malico/docker-release/internal/docker"
)

// AngieProvider is a provider for the Angie web server (a drop-in nginx replacement)
type AngieProvider struct {
	configDir     string
	docker        *docker.Client
	containerName string // angie container name for reload
}

// NewAngie creates a new Angie provider
func NewAngie(configDir string, dockerClient *docker.Client, containerName string) *AngieProvider {
	return &AngieProvider{
		configDir:     configDir,
		docker:        dockerClient,
		containerName: containerName,
	}
}

// GenerateConfig creates an Angie upstream configuration file
func (p *AngieProvider) GenerateConfig(state *UpstreamState) error {
	conf := renderAngieUpstream(state)

	if err := os.MkdirAll(p.configDir, 0o755); err != nil {
		return fmt.Errorf("creating config dir: %w", err)
	}

	path := filepath.Join(p.configDir, state.Service+".conf")
	tmp := path + ".tmp"

	if err := os.WriteFile(tmp, []byte(conf), 0o644); err != nil {
		return fmt.Errorf("writing config: %w", err)
	}

	if err := os.Rename(tmp, path); err != nil {
		return fmt.Errorf("renaming config: %w", err)
	}

	return nil
}

// Reload signals Angie to reload its configuration
func (p *AngieProvider) Reload() error {
	if p.containerName == "" {
		return nil
	}

	ctx := context.Background()

	containerID, err := p.docker.FindContainerByService(ctx, p.containerName)
	if err != nil {
		return fmt.Errorf("resolving angie container %q: %w", p.containerName, err)
	}

	return p.docker.Exec(ctx, containerID, []string{"angie", "-s", "reload"})
}

// renderAngieUpstream generates the upstream block for Angie
// Angie is a drop-in replacement for nginx, so the syntax is identical
func renderAngieUpstream(state *UpstreamState) string {
	var b strings.Builder

	fmt.Fprintf(&b, "# Generated by docker-release for Angie\n")
	fmt.Fprintf(&b, "upstream %s_upstream {\n", state.ResolveUpstreamName())

	if state.Affinity == "ip" || state.Affinity == "cookie" {
		fmt.Fprintf(&b, "    ip_hash;\n")
	} else {
		fmt.Fprintf(&b, "    least_conn;\n")
	}

	for _, s := range state.Servers {
		fmt.Fprintf(&b, "    server %s", s.Addr)

		if s.Down {
			fmt.Fprintf(&b, " down")
		} else if s.Weight > 0 {
			fmt.Fprintf(&b, " weight=%d", s.Weight)
		}

		fmt.Fprintf(&b, ";\n")
	}

	if state.Keepalive > 0 {
		fmt.Fprintf(&b, "    keepalive %d;\n", state.Keepalive)
	}

	fmt.Fprintf(&b, "}\n")

	return b.String()
}
