package provider

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/malico/docker-release/internal/docker"
)

type CaddyProvider struct {
	configDir   string
	docker      *docker.Client
	serviceName string
	path        string // optional: generate handle_path block instead of named snippet
}

func NewCaddy(configDir string, dockerClient *docker.Client, serviceName, path string) *CaddyProvider {
	return &CaddyProvider{
		configDir:   configDir,
		docker:      dockerClient,
		serviceName: serviceName,
		path:        path,
	}
}

func (p *CaddyProvider) GenerateConfig(state *UpstreamState) error {
	if err := state.Validate(); err != nil {
		return err
	}

	conf := renderCaddyUpstream(state, p.path)

	if err := os.MkdirAll(p.configDir, 0o755); err != nil {
		return fmt.Errorf("creating config dir: %w", err)
	}

	path := filepath.Join(p.configDir, state.Service+".caddy")
	tmp := path + ".tmp"

	if err := os.WriteFile(tmp, []byte(conf), 0o644); err != nil {
		return fmt.Errorf("writing config: %w", err)
	}

	if err := os.Rename(tmp, path); err != nil {
		return fmt.Errorf("renaming config: %w", err)
	}

	return nil
}

func (p *CaddyProvider) Reload() error {
	if p.serviceName == "" {
		return nil
	}

	ctx := context.Background()

	ctr, err := p.docker.FindContainerByService(ctx, p.serviceName)
	if err != nil {
		return fmt.Errorf("resolving caddy container %q: %w", p.serviceName, err)
	}

	if !matchesImage(ctr.Image, "caddy", "alpine") {
		return fmt.Errorf("container %q has unexpected image %q (want caddy or alpine-based)", p.serviceName, ctr.Image)
	}

	return p.docker.Exec(ctx, ctr.ID, []string{"caddy", "reload", "--config", "/etc/caddy/Caddyfile"})
}

func renderCaddyUpstream(state *UpstreamState, path string) string {
	var b strings.Builder

	name := state.ResolveUpstreamName()

	fmt.Fprintf(&b, "# Generated by docker-release for Caddy\n")

	if path != "" {
		fmt.Fprintf(&b, "handle_path %s* {\n", path)
	} else {
		fmt.Fprintf(&b, "(%s_upstream) {\n", name)
	}

	fmt.Fprintf(&b, "    reverse_proxy")

	var active []Server
	for _, s := range state.Servers {
		if !s.Down {
			active = append(active, s)
		}
	}

	for _, s := range active {
		fmt.Fprintf(&b, " %s", s.Addr)
	}
	fmt.Fprintf(&b, " {\n")

	hasWeights := false
	for _, s := range active {
		if s.Weight > 0 {
			hasWeights = true
			break
		}
	}

	if hasWeights {
		fmt.Fprintf(&b, "        lb_policy weighted_round_robin")
		for _, s := range active {
			w := s.Weight
			if w == 0 {
				w = 1
			}
			fmt.Fprintf(&b, " %d", w)
		}
		fmt.Fprintf(&b, "\n")
	} else {
		switch state.Affinity {
		case "cookie":
			fmt.Fprintf(&b, "        lb_policy cookie _srv\n")
		case "ip":
			fmt.Fprintf(&b, "        lb_policy ip_hash\n")
		default:
			fmt.Fprintf(&b, "        lb_policy round_robin\n")
		}
	}

	if state.Keepalive > 0 {
		fmt.Fprintf(&b, "        transport http {\n")
		fmt.Fprintf(&b, "            keepalive_idle_conns_per_host %d\n", state.Keepalive)
		fmt.Fprintf(&b, "        }\n")
	}

	fmt.Fprintf(&b, "    }\n")
	fmt.Fprintf(&b, "}\n")

	return b.String()
}
