package provider

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestCaddyRenderUpstreamBasic(t *testing.T) {
	state := &UpstreamState{
		Service: "app",
		Servers: []Server{
			{Addr: "172.18.0.5:80"},
			{Addr: "172.18.0.6:80"},
		},
	}

	got := renderCaddyUpstream(state, "")

	if !strings.Contains(got, "# Generated by docker-release for Caddy") {
		t.Error("missing Caddy header")
	}
	if !strings.Contains(got, "(app_upstream) {") {
		t.Error("missing named snippet block")
	}
	if !strings.Contains(got, "172.18.0.5:80") {
		t.Error("missing server 1")
	}
	if !strings.Contains(got, "172.18.0.6:80") {
		t.Error("missing server 2")
	}
	if !strings.Contains(got, "lb_policy round_robin") {
		t.Error("missing default round_robin policy")
	}
}

func TestCaddyRenderUpstreamCookieAffinity(t *testing.T) {
	state := &UpstreamState{
		Service:  "app",
		Affinity: "cookie",
		Servers:  []Server{{Addr: "172.18.0.5:80"}},
	}

	got := renderCaddyUpstream(state, "")

	if !strings.Contains(got, "lb_policy cookie _srv") {
		t.Error("missing cookie affinity policy")
	}
	if strings.Contains(got, "round_robin") {
		t.Error("round_robin should not appear with cookie affinity")
	}
}

func TestCaddyRenderUpstreamIPAffinity(t *testing.T) {
	state := &UpstreamState{
		Service:  "app",
		Affinity: "ip",
		Servers:  []Server{{Addr: "172.18.0.5:80"}},
	}

	got := renderCaddyUpstream(state, "")

	if !strings.Contains(got, "lb_policy ip_hash") {
		t.Error("missing ip_hash policy")
	}
}

func TestCaddyRenderUpstreamWeighted(t *testing.T) {
	state := &UpstreamState{
		Service:  "app",
		Affinity: "cookie",
		Servers: []Server{
			{Addr: "172.18.0.5:80", Weight: 75},
			{Addr: "172.18.0.6:80", Weight: 75},
			{Addr: "172.18.0.8:80", Weight: 25},
		},
	}

	got := renderCaddyUpstream(state, "")

	if !strings.Contains(got, "lb_policy weighted_round_robin") {
		t.Error("missing weighted_round_robin policy")
	}
	if strings.Contains(got, "lb_policy cookie") {
		t.Error("cookie policy should not appear when weights are set")
	}
	if !strings.Contains(got, "172.18.0.5:80") || !strings.Contains(got, "172.18.0.8:80") {
		t.Error("missing servers in weighted upstream")
	}
}

func TestCaddyRenderUpstreamDrain(t *testing.T) {
	state := &UpstreamState{
		Service: "app",
		Servers: []Server{
			{Addr: "172.18.0.5:80"},
			{Addr: "172.18.0.6:80", Down: true},
		},
	}

	got := renderCaddyUpstream(state, "")

	if strings.Contains(got, "172.18.0.6:80") {
		t.Error("down server should be omitted from Caddy upstream")
	}
	if !strings.Contains(got, "172.18.0.5:80") {
		t.Error("active server must be present")
	}
}

func TestCaddyRenderUpstreamKeepalive(t *testing.T) {
	state := &UpstreamState{
		Service:   "app",
		Keepalive: 8,
		Servers:   []Server{{Addr: "172.18.0.5:80"}},
	}

	got := renderCaddyUpstream(state, "")

	if !strings.Contains(got, "transport http {") {
		t.Error("missing transport block")
	}
	if !strings.Contains(got, "keepalive_idle_conns_per_host 8") {
		t.Error("missing keepalive setting")
	}
}

func TestCaddyRenderUpstreamCustomName(t *testing.T) {
	state := &UpstreamState{
		Service:      "app",
		UpstreamName: "myapp",
		Servers:      []Server{{Addr: "172.18.0.5:80"}},
	}

	got := renderCaddyUpstream(state, "")

	if !strings.Contains(got, "(myapp_upstream) {") {
		t.Error("should use UpstreamName override in snippet name")
	}
	if strings.Contains(got, "(app_upstream)") {
		t.Error("should not use service name when UpstreamName is set")
	}
}

func TestCaddyRenderUpstreamWithPath(t *testing.T) {
	state := &UpstreamState{
		Service: "linear_app",
		Servers: []Server{
			{Addr: "172.18.0.5:80"},
			{Addr: "172.18.0.6:80"},
		},
	}

	got := renderCaddyUpstream(state, "/linear")

	if !strings.Contains(got, "handle_path /linear*") {
		t.Error("missing handle_path block")
	}
	if strings.Contains(got, "(linear_app_upstream)") {
		t.Error("should not render named snippet when path is set")
	}
	if !strings.Contains(got, "172.18.0.5:80") {
		t.Error("missing server 1")
	}
}

func TestCaddyGenerateConfigWritesFile(t *testing.T) {
	dir := t.TempDir()
	p := NewCaddy(dir, nil, "", "")

	state := &UpstreamState{
		Service: "webapp",
		Servers: []Server{{Addr: "172.18.0.5:3000"}},
	}

	if err := p.GenerateConfig(state); err != nil {
		t.Fatalf("generate error: %v", err)
	}

	path := filepath.Join(dir, "webapp.caddy")
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read error: %v", err)
	}

	content := string(data)
	if !strings.Contains(content, "(webapp_upstream) {") {
		t.Error("file missing snippet block")
	}
	if !strings.Contains(content, "172.18.0.5:3000") {
		t.Error("file missing server")
	}
	if !strings.Contains(content, "# Generated by docker-release for Caddy") {
		t.Error("file missing Caddy header")
	}

	tmp := path + ".tmp"
	if _, err := os.Stat(tmp); !os.IsNotExist(err) {
		t.Error("temp file not cleaned up")
	}
}
