package provider

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/malico/docker-release/internal/docker"
)

type NginxProvider struct {
	configDir     string
	docker        *docker.Client
	containerName string // nginx container name for reload
}

func NewNginx(configDir string, dockerClient *docker.Client, containerName string) *NginxProvider {
	return &NginxProvider{
		configDir:     configDir,
		docker:        dockerClient,
		containerName: containerName,
	}
}

func (p *NginxProvider) GenerateConfig(state *UpstreamState) error {
	conf := renderUpstream(state)

	if err := os.MkdirAll(p.configDir, 0o755); err != nil {
		return fmt.Errorf("creating config dir: %w", err)
	}

	path := filepath.Join(p.configDir, state.Service+".conf")
	tmp := path + ".tmp"

	if err := os.WriteFile(tmp, []byte(conf), 0o644); err != nil {
		return fmt.Errorf("writing config: %w", err)
	}

	if err := os.Rename(tmp, path); err != nil {
		return fmt.Errorf("renaming config: %w", err)
	}

	return nil
}

func (p *NginxProvider) Reload() error {
	if p.containerName == "" {
		return nil
	}

	ctx := context.Background()

	containerID, err := p.docker.FindContainerByService(ctx, p.containerName)
	if err != nil {
		return fmt.Errorf("resolving nginx container %q: %w", p.containerName, err)
	}

	return p.docker.Exec(ctx, containerID, []string{"nginx", "-s", "reload"})
}

func renderUpstream(state *UpstreamState) string {
	var b strings.Builder

	fmt.Fprintf(&b, "# Generated by docker-release\n")
	fmt.Fprintf(&b, "upstream %s_upstream {\n", state.ResolveUpstreamName())

	if state.Affinity == "ip" || state.Affinity == "cookie" {
		fmt.Fprintf(&b, "    ip_hash;\n")
	}

	for _, s := range state.Servers {
		fmt.Fprintf(&b, "    server %s", s.Addr)

		if s.Down {
			fmt.Fprintf(&b, " down")
		} else if s.Weight > 0 {
			fmt.Fprintf(&b, " weight=%d", s.Weight)
		}

		fmt.Fprintf(&b, ";\n")
	}

	fmt.Fprintf(&b, "}\n")

	return b.String()
}
